### ISSUE TITLE
No issue, just wanted to say thanks for letting me assist

### ISSUE THREAD

**Issue by OgJAkFy8** [briansworth/GetIPv4Address#10]
I just posted a draft Readme.md

I have a couple other functions, that I was getting ready to post when you changed the format.  I have one that lists all the subnets and another one that pings a range of IPs, that I was able to clean up due to your work.  So, thank you for that.

I am glad to see that you change the module format, I was going to suggest that, but figured that you wanted it to be more portable. 

Big fan of the Pester.  I have been struggling with it myself and haven't had the time to work through it.  Most of my PowerShell has been working with VMware PowerCLI.  But, now that I see how pester works, it makes more sense.  

Thanks again for letting me assist with your project.

**Comment by briansworth** [comment]
I hadn't thought of or really worked on it for years until you came along, so thanks for contributing and sparking back my interest in this project!
Since I started this repository, I've realized the requirement for unit testing - so I'll be adding more unit tests and trying to get good coverage of all the publicly exposed functions.
